stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/IMDB_Dataset.csv
    outs:
    - data/raw/IMDB_Dataset.csv
  
  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
    - data/raw/IMDB_Dataset.csv
    - src/train_and_evaluate.py
    params:
    - ModelTraining.BERT.params.TRAIN_BATCH_SIZE
    - ModelTraining.BERT.params.VALID_BATCH_SIZE
    - ModelTraining.BERT.params.EPOCHS
    metrics:
    - report/scores.json:
        cache: false
    - report/params.json:
        cache: false
    outs:
    - saved_models/model.bin