base:
  project: Bert-Sentiment-Prediction
  random_state: 42
  target_col: TARGET

data_source:
  s3_source: data_given/IMDB_Dataset.csv

load_data:
  raw_dataset_csv: data/raw/IMDB_Dataset.csv

split_data:
  test_size: 0.2
  random_state: 42

ModelTraining:
  BERT:
    params:
      DEVICE: cpu
      MAX_LEN: 64
      TRAIN_BATCH_SIZE: 8
      VALID_BATCH_SIZE: 4
      EPOCHS: 10
      TEST_SIZE : 0.1
      BERT_PATH: bert-base-uncased
      MODEL_PATH: saved_models/model.bin
      TRAINING_FILE: data/raw/IMDB_Dataset.csv

model_dir: saved_models

reports:
  params: report/params.json
  scores: report/scores.json
